name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          echo "Email ${{vars.SPOTIFY_USER_EMAIL}}"
          echo "ClientId ${{vars.SPOTIFY_API_CLIENT_ID}}"
      - run: npm i
      - run: npm run build
