name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create ENV File
        run: |
          echo "Echo ENV Variables"
          echo "Email ${{vars.SPOTIFY_USER_EMAIL}}"
          echo "ClientId ${{vars.SPOTIFY_API_CLIENT_ID}}"
      - name: Create .env with Github Secrets and run script
        run: |
          touch .env
          echo ENV_VAR_1=$ENV_VAR_1 >> .env
          echo ENV_VAR_2=$ENV_VAR_2 >> .env
          npm run script-that-accesses-env-vars
        env:
          SPOTIFY_API_CLIENT_SECRET: ${{ secrets.SPOTIFY_API_CLIENT_SECRET }}
          SPOTIFY_USER_PASS: ${{ secrets.SPOTIFY_USER_PASS }}
          SPOTIFY_USER_EMAIL: ${{vars.SPOTIFY_USER_EMAIL}}
          SPOTIFY_API_CLIENT_ID: ${{vars.SPOTIFY_API_CLIENT_ID}}
      - run: npm i
      - run: npm run build
      - run: npm run ciflow
