# This is a basic workflow that is manually triggered
name: Scheduled Utility Runner

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *" #“every 8 hours.”

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "UtilRunner"
  UtilRunner:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create .env with Github Secrets and run script
        uses: iamsauravsharma/create-dotenv@v1.2.2
        env:
          LOG_TO_CONSOLE: true
          RUN_ON_HEADLESS: false
          SPOTIFY_API_CLIENT_SECRET: ${{ secrets.SPOTIFY_API_CLIENT_SECRET }}
          SPOTIFY_USER_PASS: ${{ secrets.SPOTIFY_USER_PASS }}
          SPOTIFY_USER_EMAIL: ${{ vars.SPOTIFY_USER_EMAIL}}
          SPOTIFY_API_CLIENT_ID: ${{vars.SPOTIFY_API_CLIENT_ID}}
          UNSPLASH_API_CLIENT_ID: ${{vars.UNSPLASH_API_CLIENT_ID}}
      - run: npm i
      - run: npm run ciflow
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Artfacts
          path: |
            screenshots
            token.json
            logs
